"""Guiones de la tanda 1. Cada dato lleva detrás una fuente verificada.

Estructura: gancho corto · reconocimiento · giro en la 3 · núcleo denso en la 4
· prueba en la 5 · cierre. Densidad: poco-medio-poco-MUCHO-medio-poco.
"""
import sys, os
S = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, S)
from reel2 import ESCALA as E

GUIONES = {
 "vacio": ("#e0a23c", "Redletter.mp3", [
  {"tam": E[4], "titular": "La curiosidad no nace del misterio."},
  {"kicker": "Lo que hace todo el mundo", "tam": E[3],
   "titular": "«No te vas a creer lo que pasó.»",
   "cuerpo": "Un misterio vago, sin decir de qué. Lo has visto mil veces y ya no te para."},
  {"kicker": "El giro", "tam": E[3],
   "titular": "Loewenstein lo midió en 1994.",
   "cuerpo": "La curiosidad es <i>privación</i>: aparece cuando notas un hueco concreto en lo que sabes."},
  {"kicker": "Las condiciones", "tam": E[2],
   "titular": "Por eso casi ningún gancho funciona.",
   "lista": [("Concreto", "tienes que saber QUÉ te falta, no que falta algo"),
             ("Salvable", "si parece imposible de cerrar, no hay curiosidad: hay indiferencia"),
             ("U invertida", "sin saber nada no notas el hueco; sabiéndolo todo no hay hueco"),
             ("Transitoria", "es intensa y se apaga rápido")]},
  {"kicker": "La prueba", "tam": E[3],
   "titular": "Se ve en el cerebro y en la memoria.",
   "cuerpo": "Kang midió con resonancia: la curiosidad activa el circuito de recompensa, y lo aprendido con curiosidad se recuerda dos semanas después."},
  {"tam": E[3], "titular": "Y decepciona al saciarse.",
   "cuerpo": "Lo dice el propio Loewenstein. Por eso el clickbait funciona una vez y quema para siempre."},
 ]),

 "relato": ("#e07a3c", "Echoes_of_Time_v2.mp3", [
  {"tam": E[4], "titular": "Una historia no convence. Baja la guardia."},
  {"kicker": "Lo que se repite", "tam": E[3],
   "titular": "«Cuenta historias y te comprarán.»",
   "cuerpo": "El consejo más repetido de los últimos veinte años. Es verdad a medias."},
  {"kicker": "El giro", "tam": E[3],
   "titular": "Green y Brock, 2000: el lector transportado deja de rebatir.",
   "cuerpo": "No es que se convenza más rápido. Es que baja las defensas."},
  {"kicker": "Los números reales", "tam": E[2],
   "titular": "Pero ese efecto es el más débil de todos.",
   "lista": [("r = .54", "respuesta emocional — el efecto más fuerte"),
             ("r = .41", "cambio de actitud"),
             ("r = .29", "intención de actuar"),
             ("r = −.18", "reducción del pensamiento crítico — solo 7 estudios")]},
  {"kicker": "Lo incómodo", "tam": E[3],
   "titular": "Es una herramienta que apaga el juicio.",
   "cuerpo": "Funciona igual si la historia se presenta como real o como ficción. Por eso hay que usarla con cuidado."},
  {"tam": E[3], "titular": "Cuenta historias. Pero cuenta las verdaderas.",
   "cuerpo": "Metaanálisis de 76 estudios y 132 tamaños de efecto."},
 ]),

 "emocion": ("#9b7fd4", "Lightless_Dawn.mp3", [
  {"tam": E[4], "titular": "La tristeza no se comparte."},
  {"kicker": "Lo que creemos", "tam": E[3],
   "titular": "«Emociona y se hará viral.»",
   "cuerpo": "Como si todas las emociones empujaran igual. No lo hacen."},
  {"kicker": "El giro", "tam": E[3],
   "titular": "Lo que importa no es la emoción. Es la activación.",
   "cuerpo": "Berger y Milkman analizaron 6.956 artículos del New York Times durante tres meses."},
  {"kicker": "Los números", "tam": E[2],
   "titular": "Lo que activa se comparte. Lo que apaga se olvida.",
   "lista": [("+34 %", "la ira: la emoción que más empuja a compartir"),
             ("+30 %", "el asombro, y además en positivo"),
             ("−", "la tristeza: emoción desactivante, se comparte menos"),
             ("2008", "un solo periódico, tres meses: no es una ley universal")]},
  {"kicker": "Lo que se olvida contar", "tam": E[3],
   "titular": "El contenido positivo gana al negativo.",
   "cuerpo": "En conjunto se comparte más lo positivo. La ira empuja, pero no es el camino corto que parece."},
  {"tam": E[3], "titular": "No preguntes si emociona.",
   "cuerpo": "Pregunta si activa."},
 ]),

 "prueba-social": ("#7fc4a0", "The_Descent.mp3", [
  {"tam": E[4], "titular": "El dato más citado de la persuasión falló al repetirlo."},
  {"kicker": "El experimento famoso", "tam": E[3],
   "titular": "«El 75 % de los huéspedes reutiliza la toalla.»",
   "cuerpo": "Cialdini, 2008. Funcionó: la reutilización subió del 35 % al 44 %."},
  {"kicker": "El giro", "tam": E[3],
   "titular": "En Alemania lo repitieron. No salió.",
   "cuerpo": "Bohner y Schlüter, 2014, dos hoteles, 928 personas."},
  {"kicker": "Los números de la réplica", "tam": E[2],
   "titular": "El mensaje ecológico de siempre ganó.",
   "lista": [("93,3 %", "mensaje ambiental estándar"),
             ("76,5 %", "norma social descriptiva — peor"),
             ("78,0 %", "la norma «de esta misma habitación» — la peor de todas"),
             ("64,3 %", "sin ningún mensaje")]},
  {"kicker": "Por qué importa", "tam": E[3],
   "titular": "Un número grande no persuade solo.",
   "cuerpo": "Donde ya reutiliza el 80 %, no queda margen. La prueba social depende del contexto, no del porcentaje."},
  {"tam": E[3], "titular": "Un caso concreto vale más que un número redondo.",
   "cuerpo": "Y se puede comprobar."},
 ]),

 "indignacion": ("#d8353d", "Volatile_Reaction.mp3", [
  {"tam": E[4], "titular": "La indignación vende. Y arruina el negocio."},
  {"kicker": "La tentación", "tam": E[3],
   "titular": "Enfadar funciona. Eso es cierto.",
   "cuerpo": "La ira es la emoción que más empuja a compartir. Está medido."},
  {"kicker": "El giro", "tam": E[3],
   "titular": "Pero midieron qué pasa después.",
   "cuerpo": "Center for Media Engagement, 1.535 participantes, diseño experimental."},
  {"kicker": "Lo que se rompe", "tam": E[2],
   "titular": "Los titulares de indignación redujeron todo lo que importa.",
   "lista": [("↓", "intención de volver a hacer clic"),
             ("↓", "intención de comentar"),
             ("↓", "intención de pagar por el contenido"),
             ("4,58", "percepción de «noticia falsa», frente a 4,30 sin indignación")]},
  {"kicker": "La conclusión de los autores", "tam": E[3],
   "titular": "«Poco beneficio comercial.»",
   "cuerpo": "No es solo que sea feo. Es que genera menos vuelta. Incluso desde el puro egoísmo, es mal negocio."},
  {"tam": E[3], "titular": "Puedes ganar la semana y perder el año.",
   "cuerpo": "Cada vez que prometes de más, alguien aprende a no abrirte."},
 ]),

 "manipular": ("#6f9fc4", "Ossuary_6_-_Air.mp3", [
  {"tam": E[4], "titular": "Persuadir y manipular no son lo mismo."},
  {"kicker": "La excusa cómoda", "tam": E[3],
   "titular": "«Todo es persuasión.»",
   "cuerpo": "La frase que usa quien no quiere mirar la diferencia."},
  {"kicker": "El giro", "tam": E[3],
   "titular": "Sunstein la definió con precisión.",
   "cuerpo": "Manipular es esquivar la capacidad del otro de decidir por sí mismo. Persuadir es darle con qué decidir."},
  {"kicker": "Tres preguntas", "tam": E[2],
   "titular": "Antes de publicar, respóndelas.",
   "lista": [("Transparencia", "si viera por qué escribiste eso así, ¿se sentiría respetado?"),
             ("Promesa", "¿lo último cumple lo que prometió lo primero?"),
             ("Emoción", "¿lo que provocas corresponde a algo real, o lo fabricaste?"),
             ("Y una más", "¿el impacto depende de que crea algo que no es cierto?")]},
  {"kicker": "El matiz duro", "tam": E[3],
   "titular": "Cuanto mejor funciona, peor es.",
   "cuerpo": "Sunstein lo dice así: cuanto más eficaz es el intento de esquivar la deliberación, más fuerte es la objeción ética."},
  {"tam": E[3], "titular": "La técnica no decide. Tú decides.",
   "cuerpo": "Las mismas palancas sirven para explicar o para engañar."},
 ]),
}
