"""Once guiones con datos verificados en fuente primaria por los dos agentes."""
import sys, os
S = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, S)
from reel2 import ESCALA as E

G = {
 "poses-poder": ("#9a8fb0", "Anguish.mp3", [
  {"tam": E[4], "titular": "La coautora desmintió su propio estudio."},
  {"kicker": "Lo que se enseña", "tam": E[3], "titular": "«Ponte en pose de poder dos minutos.»",
   "cuerpo": "Sube la testosterona, baja el cortisol, te arriesgas más. Está en mil cursos."},
  {"kicker": "El giro", "tam": E[3], "titular": "El original tenía 42 personas.",
   "cuerpo": "La réplica de 2015 tuvo 200, con experimentador ciego y potencia superior al 95 %."},
  {"kicker": "Lo que replicó y lo que no", "tam": E[2],
   "titular": "Solo sobrevivió la sensación.",
   "lista": [("Sentirse poderoso", "sí replicó · d = 0,34"),
             ("Testosterona", "no · p = 0,162"),
             ("Cortisol", "no · p = 0,272"),
             ("Tomar riesgos", "no · p = 0,215")]},
  {"kicker": "Sus palabras", "tam": E[3], "titular": "«No creo que los efectos sean reales.»",
   "cuerpo": "Dana Carney, coautora del original: «Los datos son endebles. Desaconsejo que otros lo estudien. Ya no lo enseño en mis clases.»"},
  {"tam": E[3], "titular": "La postura cambia cómo te sientes.",
   "cuerpo": "Lo demás no aguantó."},
 ]),

 "el-nombre": ("#c9903c", "Rites.mp3", [
  {"tam": E[4], "titular": "«El sonido más dulce es tu nombre» no es un estudio."},
  {"kicker": "De dónde sale", "tam": E[3], "titular": "Es una frase de 1936.",
   "cuerpo": "Dale Carnegie la escribió en <i>Cómo ganar amigos</i>. No citó ningún dato: era retórica."},
  {"kicker": "El giro", "tam": E[3], "titular": "Cuando se comprueba, falla.",
   "cuerpo": "Poner el nombre de pila en el asunto de un email: sin efecto en aperturas ni en clics."},
  {"kicker": "Lo que sí dice la ciencia", "tam": E[2],
   "titular": "Tu cerebro distingue tu nombre. Nada más.",
   "lista": [("34,6 %", "detecta su nombre en un canal que no atiende: dos de cada tres NO"),
             ("Frontal media", "se activa al oírlo — es autorreferencia, no placer"),
             ("Espurio", "el «efecto letra del nombre» se desmontó en 2011"),
             ("Cero", "el test aplicado más directo no encontró mejora")]},
  {"kicker": "Por qué importa", "tam": E[3], "titular": "Del reconocimiento a la persuasión hay un salto.",
   "cuerpo": "Un salto que nadie ha demostrado. Y la evidencia aplicada que existe apunta a que no funciona."},
  {"tam": E[3], "titular": "Repetir su nombre no te hace convincente.",
   "cuerpo": "Escucharle, sí."},
 ]),

 "ratio-ventas": ("#b0763c", "Clash_Defiant.mp3", [
  {"tam": E[4], "titular": "La regla del 43/57 la enterró quien la inventó."},
  {"kicker": "El dato que todos citan", "tam": E[3], "titular": "«Habla el 43 %, escucha el 57 %.»",
   "cuerpo": "Aparece en todos los cursos de venta desde 2016."},
  {"kicker": "El giro", "tam": E[3], "titular": "Gong lo actualizó en marzo de 2025.",
   "cuerpo": "Con 326.000 llamadas nuevas. Y el número cambió de bando."},
  {"kicker": "Los números de hoy", "tam": E[2], "titular": "El 57 % es lo que HABLA, no lo que escucha.",
   "lista": [("57 %", "tiempo hablando en llamadas que se cierran"),
             ("62 %", "en las que se pierden"),
             ("60 / 40", "la media de todas las llamadas"),
             ("Ojo", "dato de una empresa de software, sin revisión por pares")]},
  {"kicker": "Lo que sí está medido", "tam": E[3], "titular": "Escuchar bien correlaciona con vender.",
   "cuerpo": "Metaanálisis de 400.020 observaciones: r = 0,21 con rendimiento en ventas. Pero mide CALIDAD de escucha, no porcentaje de tiempo."},
  {"tam": E[3], "titular": "No cuentes minutos. Escucha de verdad.",
   "cuerpo": "No es lo mismo."},
 ]),

 "escuchar": ("#8fb8d0", "The_Descent.mp3", [
  {"tam": E[4], "titular": "Once segundos."},
  {"kicker": "El estudio", "tam": E[3], "titular": "Grabaron 112 consultas médicas reales.",
   "cuerpo": "Querían saber si el médico deja al paciente contar su problema."},
  {"kicker": "El giro", "tam": E[3], "titular": "Solo el 36 % llegó a preguntar por él.",
   "cuerpo": "Y de esos, el 67 % interrumpió antes de que terminara."},
  {"kicker": "Los números exactos", "tam": E[2], "titular": "Once segundos de mediana.",
   "lista": [("11 s", "mediana hasta la interrupción · rango de 3 a 234"),
             ("6 s", "lo que tardaba en exponerlo quien NO fue interrumpido"),
             ("49 %", "preguntó en atención primaria"),
             ("20 %", "preguntó en especialidades")]},
  {"kicker": "El matiz honesto", "tam": E[3], "titular": "Es mediana, no media.",
   "cuerpo": "Y solo cuenta las consultas donde el médico llegó a preguntar. Decir «interrumpen a los 11 segundos» a secas exagera el dato."},
  {"tam": E[3], "titular": "Seis segundos era todo lo que necesitaba.",
   "cuerpo": "Casi nadie se los dio."},
 ]),

 "preguntas": ("#c9a227", "Heroic_Age.mp3", [
  {"tam": E[4], "titular": "Preguntar gusta. Y nadie lo espera."},
  {"kicker": "Lo que hacemos", "tam": E[3], "titular": "Hablar de nosotros para caer bien.",
   "cuerpo": "Es el instinto. Y es el error."},
  {"kicker": "El giro", "tam": E[3], "titular": "No es preguntar. Es preguntar OTRA vez.",
   "cuerpo": "Las preguntas de seguimiento —las que continúan lo que el otro acaba de decir— son las que funcionan."},
  {"kicker": "Los datos", "tam": E[2], "titular": "Se midió en citas rápidas reales.",
   "lista": [("1.961", "citas observadas · 110 participantes"),
             ("+", "quien hace más preguntas de seguimiento consigue más segundas citas"),
             ("Nadie", "los participantes no anticipaban que preguntar aumentase la simpatía"),
             ("2025", "el estudio recibió una corrección: los errores no cambian las conclusiones")]},
  {"kicker": "Por qué cuesta", "tam": E[3], "titular": "Preguntar parece pasivo.",
   "cuerpo": "Y es lo contrario: exige escuchar lo suficiente para tener algo que preguntar."},
  {"tam": E[3], "titular": "La segunda pregunta es la que cuenta.",
   "cuerpo": "La primera la hace cualquiera."},
 ]),

 "negociar": ("#b0763c", "Redletter.mp3", [
  {"tam": E[4], "titular": "Quien dice la primera cifra, gana."},
  {"kicker": "Lo que se cree", "tam": E[3], "titular": "«Nunca abras tú.»",
   "cuerpo": "El consejo de negociación más repetido. Y está al revés."},
  {"kicker": "El giro", "tam": E[3], "titular": "El anclaje es lo más sólido de la psicología social.",
   "cuerpo": "En una replicación con 6.344 personas y 36 muestras, funcionó en 36 de 36."},
  {"kicker": "Lo que cuesta", "tam": E[2], "titular": "Pero tiene precio, y está medido.",
   "lista": [("g = 0,42", "ventaja de mover primero"),
             ("g = 1,14", "las ofertas ambiciosas mejoran el acuerdo"),
             ("g = 0,42", "…y aumentan las rupturas de negociación"),
             ("g = 0,40", "…y empeoran la satisfacción del otro")]},
  {"kicker": "Cómo se defiende", "tam": E[3], "titular": "El ancla se rompe con información.",
   "cuerpo": "En el original, la ventaja desaparecía si la otra parte se centraba en su propia alternativa o en su precio de reserva."},
  {"tam": E[3], "titular": "Abre tú. Pero cuenta lo que te va a costar.",
   "cuerpo": "Metaanálisis de 2025 · 16.334 personas."},
 ]),

 "maldicion": ("#7ea87e", "Echoes_of_Time_v2.mp3", [
  {"tam": E[4], "titular": "Creían que la mitad lo adivinaría. Acertó el 2,5 %."},
  {"kicker": "El experimento", "tam": E[3], "titular": "Golpear el ritmo de una canción con el dedo.",
   "cuerpo": "Cuarenta personas golpeaban; otras escuchaban e intentaban adivinar el título."},
  {"kicker": "El giro", "tam": E[3], "titular": "Quien golpea oye la canción en su cabeza.",
   "cuerpo": "Quien escucha solo oye golpes. Y el que golpea no puede dejar de oírla."},
  {"kicker": "Los números", "tam": E[2], "titular": "Tres aciertos en ciento veinte intentos.",
   "lista": [("50 %", "lo que los golpeadores predijeron que se adivinaría"),
             ("2,5 %", "lo que se adivinó de verdad"),
             ("3 / 120", "aciertos totales"),
             ("1990", "tesis de Stanford, nunca publicada en revista")]},
  {"kicker": "Un detalle revelador", "tam": E[3], "titular": "Ni el título se cita bien.",
   "cuerpo": "Todo internet lo llama «Overconfidence in the communication of intent». El título real es «The rocky road from actions to intentions»."},
  {"tam": E[3], "titular": "Tú oyes la canción. Ellos oyen golpes.",
   "cuerpo": "Eso es toda la explicación."},
 ]),

 "silencio": ("#a8b0b8", "Lightless_Dawn.mp3", [
  {"tam": E[4], "titular": "Cuatro segundos de silencio que nadie nota."},
  {"kicker": "Lo que se dice", "tam": E[3], "titular": "«A los cuatro segundos se hace incómodo.»",
   "cuerpo": "El dato circula por todas partes. La cifra es real. La interpretación, no."},
  {"kicker": "El giro", "tam": E[3], "titular": "Eligieron cuatro segundos precisamente porque no se notan.",
   "cuerpo": "Lo dicen en el propio artículo: buscaban una pausa que pasara desapercibida."},
  {"kicker": "Lo que midieron", "tam": E[2], "titular": "El malestar es inconsciente.",
   "lista": [("2,80", "sensación de rechazo con la pausa · frente a 1,83 sin ella"),
             ("3,32", "emociones negativas · frente a 2,01"),
             ("↓", "pertenencia, autoestima y validación social"),
             ("60", "participantes · un vídeo de seis minutos")]},
  {"kicker": "Lo que significa", "tam": E[3], "titular": "No lo notas. Te afecta igual.",
   "cuerpo": "Nadie salió diciendo «hubo un silencio raro». Salieron sintiéndose menos incluidos."},
  {"tam": E[3], "titular": "El silencio no incomoda. Excluye.",
   "cuerpo": "Y no te enteras."},
 ]),

 "decir-no": ("#c25b4e", "Volatile_Reaction.mp3", [
  {"tam": E[4], "titular": "«No lo hago» funciona. «No puedo» no."},
  {"kicker": "La diferencia", "tam": E[3], "titular": "Dos formas de rechazar lo mismo.",
   "cuerpo": "«No puedo comer eso» te pone una regla externa. «No como eso» te define."},
  {"kicker": "El giro", "tam": E[3], "titular": "Cambia quién manda.",
   "cuerpo": "Una es una restricción que sufres. La otra es una decisión que tomaste."},
  {"kicker": "Los números", "tam": E[2], "titular": "Diez días de seguimiento.",
   "lista": [("8 de 10", "aguantaron los diez días diciendo «no lo hago»"),
             ("1 de 10", "aguantaron diciendo «no puedo»"),
             ("3 de 10", "aguantaron con un «simplemente di no»"),
             ("64 % / 39 %", "elección saludable en el primer experimento")]},
  {"kicker": "El matiz que hay que decir", "tam": E[3], "titular": "El estudio estrella tenía treinta personas.",
   "cuerpo": "Diez por condición, en 2012, sin réplica independiente. La cifra es real; la base es pequeña."},
  {"tam": E[3], "titular": "Cambia una palabra. Cambia de quién es la decisión.",
   "cuerpo": ""},
 ]),

 "objeciones": ("#c9903c", "Ossuary_6_-_Air.mp3", [
  {"tam": E[4], "titular": "Admitir un fallo sube tu credibilidad un 0,8 %."},
  {"kicker": "El consejo habitual", "tam": E[3], "titular": "«Reconoce tus debilidades y te creerán.»",
   "cuerpo": "Suena bien. Está medido. Y el efecto es diminuto."},
  {"kicker": "El giro", "tam": E[3], "titular": "Depende de si además la refutas.",
   "cuerpo": "Ahí está toda la diferencia, y casi nadie lo cuenta."},
  {"kicker": "Los números", "tam": E[2], "titular": "Metaanálisis de 107 estudios.",
   "lista": [("r = .09", "subida de credibilidad · menos del 1 % de la varianza"),
             ("r = −.001", "efecto sobre la persuasión: cero"),
             ("r = .077", "si REFUTAS la objeción: funciona"),
             ("r = −.049", "si solo la admites: eres MENOS persuasivo")]},
  {"kicker": "La regla que sale de ahí", "tam": E[3], "titular": "Nombrar el problema no basta.",
   "cuerpo": "Admitir sin responder te debilita. Admitir y responder te fortalece. Es una sola frase de diferencia."},
  {"tam": E[3], "titular": "Di la objeción. Y contéstala.",
   "cuerpo": "Lo primero sin lo segundo juega en tu contra."},
 ]),

 "inoculacion": ("#6fa88f", "Rites.mp3", [
  {"tam": E[4], "titular": "Contra el engaño funciona lo mismo que contra un virus."},
  {"kicker": "La idea", "tam": E[3], "titular": "McGuire, años sesenta.",
   "cuerpo": "Expones a alguien a una versión débil del argumento contrario, y queda resistente al fuerte."},
  {"kicker": "El giro", "tam": E[3], "titular": "No se enseña el bulo. Se enseña la técnica.",
   "cuerpo": "No adviertes de una mentira concreta: enseñas a reconocer cómo se manipula."},
  {"kicker": "Probado a escala", "tam": E[2], "titular": "Cinco vídeos cortos, decenas de miles de personas.",
   "lista": [("6.464", "participantes en 6 ensayos aleatorizados"),
             ("22.632", "personas en un estudio de campo en YouTube"),
             ("↑", "mejor reconocimiento de manipulación, en todo el espectro político"),
             ("d = 0,23", "efecto sobre la intención de compartir: pequeño")]},
  {"kicker": "El límite", "tam": E[3], "titular": "Los efectos son pequeños y a corto plazo.",
   "cuerpo": "Funciona, pero no es un escudo permanente. Y el metaanálisis que da esas cifras es todavía un preprint."},
  {"tam": E[3], "titular": "Avisa antes. Después ya es tarde.",
   "cuerpo": ""},
 ]),
}
